import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

const sharedConfig = {
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
};

const pluginContext = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["main.ts"],
	...sharedConfig,
	format: "cjs",
	target: "es2018",
	outfile: "main.js",
});

const cliContext = await esbuild.context({
	entryPoints: ["src/cli/index.ts"],
	...sharedConfig,
	// CLI does not bundle obsidian or electron; all node builtins are external
	// The 'external' from sharedConfig is for the plugin, override it for the CLI.
	external: [...builtins],
	format: "cjs",
	target: "node18",
	platform: "node",
	outfile: "fit-cli.cjs",
});

if (prod) {
	await pluginContext.rebuild();
	await cliContext.rebuild();
	process.exit(0);
} else {
	await pluginContext.watch();
	await cliContext.watch();
}